---

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TestAndLinter
    displayName: Lint .::. Test .::. Coverage
    jobs:
      - job: Test
        displayName: Tests
        steps:
        - task: NodeTool@0
          displayName: 'Install Node.js v16.x'
          inputs:
            versionSpec: '16.x'

        - task: Npm@1
          displayName: 'Install dependencies'
          continueOnError: false
          inputs:
            command: 'install'

        - task: Npm@1
          displayName: 'Run build'
          continueOnError: false
          inputs:
            command: 'custom'
            customCommand: 'run build'

        - task: Npm@1
          displayName: 'Run test'
          inputs:
            command: 'custom'
            customCommand: 'run test:ci'

        - task: PublishTestResults@2
          displayName: Publish Jest Unit Test results
          inputs:
            testResultsFiles: junit.xml
            mergeTestResults: true
            testRunTitle: 'Jest Unit Tests'
            failTaskOnFailedTests: true

        - task: PublishCodeCoverageResults@1
          displayName: 'Publish code coverage from Jest tests'
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            # reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
            failIfCoverageEmpty: true

      - job: Linter
        displayName: Lint
        steps:
        - task: NodeTool@0
          displayName: 'Install Node.js v16.x'
          inputs:
            versionSpec: '16.x'

        - task: Npm@1
          displayName: 'Install dependencies'
          continueOnError: false
          inputs:
            command: 'install'

        - task: Npm@1
          displayName: 'Run linter'
          inputs:
            command: 'custom'
            customCommand: 'run lint'

  - stage: Publish
    displayName: Publish Package
    dependsOn:
      - TestAndLinter
    jobs:
      - deployment: PublishPackage
        displayName: Publish
        environment: 'nextid-prd' # require admin approval
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: NodeTool@0
                displayName: 'Install Node.js v16.x'
                inputs:
                  versionSpec: '16.x'

              - task: Npm@1
                displayName: 'Install dependencies'
                continueOnError: false
                inputs:
                  workingDir: $(Build.SourcesDirectory)
                  command: 'install'

              - task: Npm@1
                displayName: 'Run build'
                continueOnError: false
                inputs:
                  workingDir: $(Build.SourcesDirectory)
                  command: 'custom'
                  customCommand: 'run build'

              - task: Npm@1
                displayName: 'Publish package'
                continueOnError: false
                inputs:
                  command: 'dist:publish:slim'
                  workingDir: $(Build.SourcesDirectory)
                  publishRegistry: 'useFeed'
                  publishFeed: 'NextID/NextidCoreLibrary'

